cd /scratch/project_2001259/cuiwang/nodelete/rawRAD/ploidypredic
ln -s /scratch/project_2001259/cuiwang/nodelete/rawRAD/process_radtags/primaryonlybam/*.bam .
for i in *.bam; do samtools mpileup -q 10 -Q 10 -s $i | awk -f pileupCounts.awk > $i\_count; done
#exclude repeat regions, 
#scp PaEUcurated.repeats.bed cuiwang@puhti.csc.fi:/scratch/project_2001259/cuiwang/nodelete/rawRAD/ploidypredic
for i in `ls *.bam | sed 's/\.bam//g' `; do bedtools intersect -abam $i".bam" -b PaEUcurated.repeats.bed -v > $i"_filtered.bam"; done
for i in `ls *_filtered.bam | sed 's/\_filtered.bam//g' `; do samtools mpileup -q 10 -Q 10 -s $i"_filtered.bam" | awk -f pileupCountsV2.awk > $i\_count; done
for i in `ls *_filtered.bam_count | sed 's/\_filtered.bam_count//g' `; do cat $i"_filtered.bam_count" | awk '{print $4/($4 + $3)}' > $i".bam_count_alter_allefreq"; done
#for predicted tetraploids, allele depth 10
setwd("/Users/cuiwang/Google Drive/My Drive/Phragmites RAD/allele_count/countV2")
pdf(file="tetraploids.pdf")
Y4<-read.table("Y4.bam_count_alter_allefreq")
Y4<- density(Y4$V1)
plot(Y4,col="turquoise", lty=1,ylim=c(0,4), xlab="Alternative allele frequency", main="Tetraploids", lwd=5)
Y10<-read.table("Y10.bam_count_alter_allefreq")
Y10<- density(Y10$V1)
lines(Y10,col="turquoise", lty=1,lwd=5)
Y11<-read.table("Y11.bam_count_alter_allefreq")
Y11<- density(Y11$V1)
lines(Y11,col="turquoise", lty=1,lwd=5)
Y13<-read.table("Y13.bam_count_alter_allefreq")
Y13<- density(Y13$V1)
lines(Y13,col="turquoise", lty=1,lwd=5)
Y14<-read.table("Y14.bam_count_alter_allefreq")
Y14<- density(Y14$V1)
lines(Y14,col="turquoise", lty=1,lwd=5)
Y15<-read.table("Y15.bam_count_alter_allefreq")
Y15<- density(Y15$V1)
lines(Y15,col="turquoise", lty=1,lwd=5)
Y16<-read.table("Y16.bam_count_alter_allefreq")
Y16<- density(Y16$V1)
lines(Y16,col="turquoise", lty=1,lwd=5)
#Y17<-read.table("Y17_1.bam_count_alter_allefreq")
#Y17<- density(Y17$V1)
#lines(Y17,col="turquoise", lty=1,lwd=5)
Y18<-read.table("Y18.bam_count_alter_allefreq")
Y18<- density(Y18$V1)
lines(Y18,col="turquoise", lty=1,lwd=5)
Y19<-read.table("Y19.bam_count_alter_allefreq")
Y19<- density(Y19$V1)
lines(Y19,col="turquoise", lty=1,lwd=5)
Y20<-read.table("Y20.bam_count_alter_allefreq")
Y20<- density(Y20$V1)
lines(Y20,col="turquoise", lty=1,lwd=5)
Y22<-read.table("Y22.bam_count_alter_allefreq")
Y22<- density(Y22$V1)
lines(Y22,col="turquoise", lty=1,lwd=5)
Y23<-read.table("Y23.bam_count_alter_allefreq")
Y23<- density(Y23$V1)
lines(Y23,col="turquoise", lty=1,lwd=5)
Y24<-read.table("Y24.bam_count_alter_allefreq")
Y24<- density(Y24$V1)
lines(Y24,col="turquoise", lty=2,lwd=5)
#Y27<-read.table("Y27.bam_count_alter_allefreq")
#Y27<- density(Y27$V1)
#lines(Y27,col="turquoise", lty=1,lwd=5)
Y28<-read.table("Y28.bam_count_alter_allefreq")
Y28<- density(Y28$V1)
lines(Y28,col="turquoise", lty=2,lwd=5)
Y31<-read.table("Y31.bam_count_alter_allefreq")
Y31<- density(Y31$V1)
lines(Y31,col="turquoise", lty=2,lwd=5)
Y32<-read.table("Y32.bam_count_alter_allefreq")
Y32<- density(Y32$V1)
lines(Y32,col="turquoise", lty=2,lwd=5)
Y34<-read.table("Y34.bam_count_alter_allefreq")
Y34<- density(Y34$V1)
lines(Y34,col="turquoise", lty=2,lwd=5)
Y38<-read.table("Y38.bam_count_alter_allefreq")
Y38<- density(Y38$V1)
lines(Y38,col="turquoise", lty=2,lwd=5)
Y40<-read.table("Y40.bam_count_alter_allefreq")
Y40<- density(Y40$V1)
lines(Y40,col="turquoise", lty=2,lwd=5)
Y41<-read.table("Y41.bam_count_alter_allefreq")
Y41<- density(Y41$V1)
lines(Y41,col="turquoise", lty=2,lwd=5)
Y45<-read.table("Y45.bam_count_alter_allefreq")
Y45<- density(Y45$V1)
lines(Y45,col="turquoise", lty=2,lwd=5)
Y46<-read.table("Y46.bam_count_alter_allefreq")
Y46<- density(Y46$V1)
lines(Y46,col="turquoise", lty=2,lwd=5)
Y47<-read.table("Y47.bam_count_alter_allefreq")
Y47<- density(Y47$V1)
lines(Y47,col="turquoise", lty=2,lwd=5)
Y55<-read.table("Y55.bam_count_alter_allefreq")
Y55<- density(Y55$V1)
lines(Y55,col="turquoise", lty=2,lwd=5)
Y57<-read.table("Y57.bam_count_alter_allefreq")
Y57<- density(Y57$V1)
lines(Y57,col="turquoise", lty=2,lwd=5)
A2<-read.table("A2.bam_count_alter_allefreq")
A2<- density(A2$V1)
lines(A2,col="turquoise", lty=1,lwd=5)
A3<-read.table("A3.bam_count_alter_allefreq")
A3<- density(A3$V1)
lines(A3,col="turquoise", lty=1,lwd=5)
A9<-read.table("A9.bam_count_alter_allefreq")
A9<- density(A9$V1)
lines(A9,col="turquoise", lty=2,lwd=5)
A10<-read.table("A10.bam_count_alter_allefreq")
A10<- density(A10$V1)
lines(A10,col="turquoise", lty=1,lwd=5)
C9<-read.table("C9.bam_count_alter_allefreq")
C9<- density(C9$V1)
lines(C9,col="turquoise", lty=1,lwd=5)
C10<-read.table("C10.bam_count_alter_allefreq")
C10<- density(C10$V1)
lines(C10,col="turquoise", lty=1,lwd=5)
C11<-read.table("C11.bam_count_alter_allefreq")
C11<- density(C11$V1)
lines(C11,col="turquoise", lty=1,lwd=5)
C12<-read.table("C12.bam_count_alter_allefreq")
C12<- density(C12$V1)
lines(C12,col="turquoise", lty=1,lwd=5)
C13<-read.table("C13.bam_count_alter_allefreq")
C13<- density(C13$V1)
lines(C13,col="turquoise", lty=1,lwd=5)
D4<-read.table("D4.bam_count_alter_allefreq")
D4<- density(D4$V1)
lines(D4,col="turquoise", lty=1,lwd=5)
D5<-read.table("D5.bam_count_alter_allefreq")
D5<- density(D5$V1)
lines(D5,col="turquoise", lty=2,lwd=5)
D6<-read.table("D6.bam_count_alter_allefreq")
D6<- density(D6$V1)
lines(D6,col="turquoise", lty=2,lwd=5)
D7<-read.table("D7.bam_count_alter_allefreq")
D7<- density(D7$V1)
lines(D7,col="turquoise", lty=1,lwd=5)
D9<-read.table("D9.bam_count_alter_allefreq")
D9<- density(D9$V1)
lines(D9,col="turquoise", lty=1,lwd=5)
D11<-read.table("D11.bam_count_alter_allefreq")
D11<- density(D11$V1)
lines(D11,col="turquoise", lty=1,lwd=5)
D12<-read.table("D12.bam_count_alter_allefreq")
D12<- density(D12$V1)
lines(D12,col="turquoise", lty=1,lwd=5)
D13<-read.table("D13.bam_count_alter_allefreq")
D13<- density(D13$V1)
lines(D13,col="turquoise", lty=1,lwd=5)
E3<-read.table("E3.bam_count_alter_allefreq")
E3<- density(E3$V1)
lines(E3,col="turquoise", lty=2,lwd=5)
E9<-read.table("E9.bam_count_alter_allefreq")
E9<- density(E9$V1)
lines(E9,col="turquoise", lty=1,lwd=5)
#E12<-read.table("E12.bam_count_alter_allefreq")
#E12<- density(E12$V1)
#lines(E12,col="turquoise", lty=1,lwd=5)
E13<-read.table("E13.bam_count_alter_allefreq")
E13<- density(E13$V1)
lines(E13,col="turquoise", lty=1,lwd=5)
F9<-read.table("F9.bam_count_alter_allefreq")
F9<- density(F9$V1)
lines(F9,col="turquoise", lty=2,lwd=5)
F13<-read.table("F13.bam_count_alter_allefreq")
F13<- density(F13$V1)
lines(F13,col="turquoise", lty=2,lwd=5)
H5<-read.table("H5.bam_count_alter_allefreq")
H5<- density(H5$V1)
lines(H5,col="turquoise", lty=2,lwd=5)
H6<-read.table("H6.bam_count_alter_allefreq")
H6<- density(H6$V1)
lines(H6,col="turquoise", lty=1,lwd=5)
I12<-read.table("I12.bam_count_alter_allefreq")
I12<- density(I12$V1)
lines(I12,col="turquoise", lty=1,lwd=5)
K12<-read.table("K12.bam_count_alter_allefreq")
K12<- density(K12$V1)
lines(K12,col="turquoise", lty=1,lwd=5)
Y21<-read.table("Y21.bam_count_alter_allefreq")
Y21<- density(Y21$V1)
lines(Y21,col="turquoise", lty=2,lwd=5)
Y26<-read.table("Y26.bam_count_alter_allefreq")
Y26<- density(Y26$V1)
lines(Y26,col="turquoise", lty=2,lwd=5)
dev.off()

#check , use the parameter in pileupCountsV2.awk to calculate for these individuals
samtools mpileup -q 30 -Q 30 -s Y17_1.bam | awk -f pileupCounts.awk > Y17_1.bam_count
samtools mpileup -q 10 -Q 10 -s Y27.bam | awk -f pileupCountsV2.awk > Y27.bam_count
samtools mpileup -q 10 -Q 10 -s E12.bam | awk -f pileupCountsV2.awk > E12.bam_count
samtools mpileup -q 10 -Q 10 -s Y21.bam | awk -f pileupCountsV2.awk > Y21.bam_count
samtools mpileup -q 10 -Q 10 -s Y26.bam | awk -f pileupCountsV2.awk > Y26.bam_count
cat Y17_1.bam_count | awk '{print $4/($4 + $3)}' > Y17_1.bam_count_alter_allefreq
cat E12.bam_count | awk '{print $4/($4 + $3)}' > E12.bam_count_alter_allefreq
cat Y21.bam_count | awk '{print $4/($4 + $3)}' > Y21.bam_count_alter_allefreq

pdf(file="USnat.pdf")
Y17<-read.table("Y17_1.bam_count_alter_allefreq")
Y17<- density(Y17$V1)
plot(Y17,col="turquoise", lty=1,ylim=c(0,4), xlab="Alternative allele frequency", main="Tetraploids", lwd=5)
Y27<-read.table("Y27.bam_count_alter_allefreq")
Y27<- density(Y27$V1)
lines(Y27,col="turquoise", lty=1,lwd=5)
E12<-read.table("E12.bam_count_alter_allefreq")
E12<- density(E12$V1)
lines(E12,col="turquoise", lty=1,lwd=5)
dev.off()

#hybrid between USnat and others
K12<-read.table("K12.bam_count_alter_allefreq")
K12<- density(K12$V1)
lines(K12,col="turquoise", lty=1,lwd=5)
#hybrid octoploid
Y48<-read.table("Y48.bam_count_alter_allefreq")
Y48<- density(Y48$V1)
lines(Y48,col="red", lty=2,lwd=5)


#use new parameter, allele depth 10, not good, forced everything to diploid
for i in *.bam; do samtools mpileup -q 10 -Q 10 -s $i | awk -f pileupCountsV2.awk > $i\_count; done
for i in *.bam; do cat $i"_count" | awk '{print $4/($4 + $3)}' > $i"_count_alter_allefreq" ; done

#octoploids, used results from V1, number of allele depth set to be 7,
setwd("/Users/cuiwang/Google Drive/My Drive/Phragmites RAD/allele_count/count")
Y1<-read.table("Y1.bam_count_alter_allefreq")
Y1<- density(Y1$V1)
plot(Y1,col="red", lty=1,ylim=c(0,4), xlab="Alternative allele frequency", main="octoploids", lwd=5)
Y3<-read.table("Y3.bam_count_alter_allefreq")
Y3<- density(Y3$V1)
lines(Y3,col="red", lty=1,lwd=5)
Y6<-read.table("Y6.bam_count_alter_allefreq")
Y6<- density(Y6$V1)
lines(Y6,col="red", lty=1,lwd=5)
Y9<-read.table("Y9.bam_count_alter_allefreq")
Y9<- density(Y9$V1)
lines(Y9,col="red", lty=2,lwd=5)
Y25<-read.table("Y25.bam_count_alter_allefreq")
Y25<- density(Y25$V1)
lines(Y25,col="red", lty=1,lwd=5)
Y36<-read.table("Y36.bam_count_alter_allefreq")
Y36<- density(Y36$V1)
lines(Y36,col="red", lty=1,lwd=5)
Y39<-read.table("Y39.bam_count_alter_allefreq")
Y39<- density(Y39$V1)
lines(Y39,col="red", lty=2,lwd=5)
Y43<-read.table("Y43.bam_count_alter_allefreq")
Y43<- density(Y43$V1)
lines(Y43,col="red", lty=2,lwd=5)
Y49<-read.table("Y49.bam_count_alter_allefreq")
Y49<- density(Y49$V1)
lines(Y49,col="red", lty=2,lwd=5)
Y51<-read.table("Y51_1.bam_count_alter_allefreq")
Y51<- density(Y51$V1)
lines(Y51,col="red", lty=2,lwd=5)
Y53<-read.table("Y53.bam_count_alter_allefreq")
Y53<- density(Y53$V1)
lines(Y53,col="red", lty=2,lwd=5)
A5<-read.table("A5.bam_count_alter_allefreq")
A5<- density(A5$V1)
lines(A5,col="red", lty=1,lwd=5)
A7<-read.table("A7.bam_count_alter_allefreq")
A7<- density(A7$V1)
lines(A7,col="red", lty=1,lwd=5)
C2<-read.table("C2.bam_count_alter_allefreq")
C2<- density(C2$V1)
lines(C2,col="red", lty=1,lwd=5)
C3<-read.table("C3.bam_count_alter_allefreq")
C3<- density(C3$V1)
lines(C3,col="red", lty=1,lwd=5)
C6<-read.table("C6.bam_count_alter_allefreq")
C6<- density(C6$V1)
lines(C6,col="red", lty=1,lwd=5)
C7<-read.table("C7.bam_count_alter_allefreq")
C7<- density(C7$V1)
lines(C7,col="red", lty=1,lwd=5)
F2<-read.table("F2.bam_count_alter_allefreq")
F2<- density(F2$V1)
lines(F2,col="red", lty=1,lwd=5)
H1<-read.table("H1.bam_count_alter_allefreq")
H1<- density(H1$V1)
lines(H1,col="red", lty=1,lwd=5)
K13<-read.table("K13.bam_count_alter_allefreq")
K13<- density(K13$V1)
lines(K13,col="red", lty=1,lwd=5)

#hexaploids, allele depth 7
Y7<-read.table("Y7.bam_count_alter_allefreq")
Y7<- density(Y7$V1)
plot(Y7,col="blue", lty=2,ylim=c(0,4), xlab="Alternative allele frequency", main="hexaploids", lwd=5)
Y12<-read.table("Y12.bam_count_alter_allefreq")
Y12<- density(Y12$V1)
lines(Y12,col="blue", lty=2,lwd=5)
Y30<-read.table("Y30.bam_count_alter_allefreq")
Y30<- density(Y30$V1)
lines(Y30,col="blue", lty=2,lwd=5)
Y33<-read.table("Y33.bam_count_alter_allefreq")
Y33<- density(Y33$V1)
lines(Y33,col="blue", lty=2,lwd=5)
Y35<-read.table("Y35.bam_count_alter_allefreq")
Y35<- density(Y35$V1)
lines(Y35,col="blue", lty=2,lwd=5)
Y37<-read.table("Y37.bam_count_alter_allefreq")
Y37<- density(Y37$V1)
lines(Y37,col="blue", lty=2,lwd=5)
Y44<-read.table("Y44.bam_count_alter_allefreq")
Y44<- density(Y44$V1)
lines(Y44,col="blue", lty=2,lwd=5)
A8<-read.table("A8.bam_count_alter_allefreq")
A8<- density(A8$V1)
lines(A8,col="blue", lty=1,lwd=5)
B2<-read.table("B2.bam_count_alter_allefreq")
B2<- density(B2$V1)
lines(B2,col="blue", lty=1,lwd=5)
H2<-read.table("H2.bam_count_alter_allefreq")
H2<- density(H2$V1)
lines(H2,col="blue", lty=1,lwd=5)
K2<-read.table("K2.bam_count_alter_allefreq")
K2<- density(K2$V1)
lines(K2,col="blue", lty=1,lwd=5)